server:
  port: 8762
spring:
  application:
    name: turing-admin
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://101.42.141.16:3306/turing-admin?characterEncoding=utf8&useSSL=false&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=GMT%2B8&nullCatalogMeansCurrent=true&allowPublicKeyRetrieval=true
    username: root
    password: wujian123
mybatis:
  basepackage: cn.turing.firecontrol.admin.mapper
  xmlLocation: classpath:mapper/**/*.xml
  mapper-locations: 'classpath:mapper/*.xml'
mapper:
  mappers: cn.turing.firecontrol.common.mapper.CommonMapper

#redis-cache 相关
redis:
  pool:
    maxActive: 300
    maxIdle: 100
    maxWait: 1000
  host: 127.0.0.1
  port: 6379
  password:
  timeout: 2000
  # 服务或应用名
  sysName: turing-admin
  enable: true
  database: 0


auth:
  serviceId: turing-auth
  user:
    token-header: Authorization
    limit-expire: 1440 # 单位：分钟
  client:
    id: turing-admin
    secret: 123456
    token-header: client-token

logging:
  level:
    tk.mybatis: DEBUG
    cn.turing.firecontrol.admin: DEBUG

#配置swagger
swagger:
  enabled: true
  base-package: cn.turing.firecontrol.admin
  title: Admin Back
  version: 1.0.0.SNAPSHOT
  description: Admin Back后端服务
  contact:
    name: 老A

# 跨服务数据合并
merge:
  enabled: true
  guavaCacheNumMaxSize: 1000
  guavaCacheRefreshWriteTime: 10 # min
  guavaCacheRefreshThreadPoolSize: 10
  aop:
    enabled: true
