server:
  port: 9777 #启动端口11111
client:
  id: turing-auth
  secret: 123456
  token-header: client-token
  expire: 3600
  rsa-secret: x2318^^(*WRYQWR(QW&T
spring:
    application:
        name: turing-auth
    datasource:
      driverClassName: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://47.96.118.225:3306/turing-auth?characterEncoding=utf8&zeroDateTimeBehavior=CONVERT_TO_NULL&useSSL=false&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=GMT%2B8&nullCatalogMeansCurrent=true&allowPublicKeyRetrieval=true
      druid:
        stat-view-servlet:
          loginUsername: root
          loginPassword: 123456
mybatis:
    basepackage: cn.turing.firecontrol.auth.mapper
    xmlLocation: classpath:mapper/**/*.xml
    mapper-locations: "classpath*:mapper/*.xml"
mapper:
  mappers: cn.turing.firecontrol.common.mapper.CommonMapper

redis:
  host: 47.96.118.225
  port: 6379
  turing-key: xx288&^^%$!@#4dc
  turing-iv: 0123456789abcdef
# 配置swagger
swagger:
    enabled: true
    base-package: cn.turing.firecontrol.auth
    title: turing-auth
    version: 1.0.0.SNAPSHOT
    description: 鉴权服务
    contact:
        name: auth

logging:
  level:
    root: info
    ## 这里设置为info，是因为如果不设置，debug时会不断打印mq日志。
    org.springframework.integration.endpoint.SourcePollingChannelAdapter: info
    org.springframework.security: info
