logging:
    level:
#       tk.mybatis: INFO
        cn.turing.firecontrol: DEBUG
server:
    port: 2222

spring:
    application:
      name: turing-device
    jackson:
      date-format: yyyy-MM-dd HH:mm:ss
      time-zone: GMT+8
      default-property-inclusion: non_null
  #  boot:
  #    admin:
  #      url: http://192.168.0.22:8766
  #      client:
  #        prefer-ip: true
    redis:
      host: 43.142.35.71
      port: 6379
      password: 123456
      database: 0
    rabbitmq:
      host: 43.142.35.71
      port: 5672
      username: guest
      password: guest
      dynamic: true
      virtual-host: /
    elasticsearch:
      cluster-name: my-application
      cluster-nodes: 127.0.0.1:9601,127.0.0.1:9602,127.0.0.1:9603
      rest:
        username: esuser
        password: Itat@pros
        uris:
          - http://127.0.0.1:9201
    datasource:
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://43.142.35.71:3306/turing-device?characterEncoding=utf8&zeroDateTimeBehavior=CONVERT_TO_NULL&useSSL=false&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=GMT%2B8&nullCatalogMeansCurrent=true&allowPublicKeyRetrieval=true
      username: root
      password: 123456
        # 初始化时建立物理连接的个数
        initial-size: 5
        # 最小链接池数量
        min-idle: 5
        # 最大连接池数量（缺省值：8）
        max-active: 20
        # 获取连接时最大等待时间，单位毫秒。
        max-wait: 60000
      druid:
        stat-view-servlet:
          loginUsername: root
          loginPassword: 123456


#配置数据库
mybatis:
    basepackage: cn.turing.firecontrol.device.mapper
    xmlLocation: classpath:mapper/**/*.xml
    mapper-locations: "classpath*:mapper/*.xml"
    configuration:
      cache-enabled: false
      map-underscore-to-camel-case: true

# 配置swagger
swagger:
    enabled: true
    base-package: cn.turing.firecontrol.device
    title: 消防大数据
    version: 1.0.0.SNAPSHOT
    description: 设备管理服务
    contact:
        name: 北京维数科技有限公司
#    global-operation-parameters[0]:
#            name: Authorization
#            description: access_token
#            modelRef: string
#            parameterType: header
#            required: true

# 配置用户认证和服务认证信息
auth:
  serviceId: turing-auth
  user:
    token-header: Authorization
    limit-expire: 1440 # 一天过去,单位分钟
  client:
    id: turing-device
    secret: 123456
    token-header: client-token

mapper:
  mappers: cn.turing.firecontrol.common.mapper.CommonMapper

# 配置萤石开放平台账号
yingShi:
  appKey:
  appSecret:

# 小花儿人工智能图像识别接口
xiaoHuaErAI:
  appCode:
  accuracyThreshold: 0.8  #accuracy>0.8 表示有很大可能发生火灾





